version: '3.8'

services:
  adorsis-mariadb:
    image: mariadb:11.8.1-ubi9-rc
    container_name: adorsis-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Management
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - adorsis-network

#  adorsis-web-api:
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - adorsis-mariadb
#    networks:
#      - adorsis-network

networks:
  adorsis-network:
    driver: bridge
